### ISSUE TITLE
Contribute here, or in octant

### ISSUE THREAD

**Issue by phobson** [hetland/pygridgen#3]
I'm curious if it is better to contribute source code changes related specific to grid generation here, or in your octant repository as they both contain the same `grid.py` and `csa.py` files.

It appears that octant would be the place, but would like to confirm.

**Comment by phobson** [comment]
@hetland 

Thanks for the thorough response, Dr. Hetland.

The latest thing I've added are some basic regression tests and some basic continuous integration (https://travis-ci.org/phobson/pygridgen). They are pretty basic, but I think it's a solid foundation upon which we can build and at the very least, make sure nothing gets completely broken in the future. I've got a several other things I would like to add, such as plotting, I/O functionality with shapefiles, and functions to stitch grids together (helpful which making very long grids along complex rivers). These already have tests and will fit in nicely with what is current in my "develop" branch.

Point of all that is, I think we should start with the testing commits and then all of the other minor clean up stuff, and then all of the other bells and whistles, should they also be welcome.

**Comment by hetland** [comment]
OK, so we will commit pygridgen stuff here. Please send along any pull requests, and I will make sure this repository keeps up to date with your changes.

I think that creating a very basic set of unit tests is a good idea, and 'minor cleanup' is probably a priority right now.

One issues I would like to resolve is the way that the `gridgen` library is loaded. I think the way it is done now is not the best. We should look at how other packages do this, like `basemap`'s use of the `proc` library would be a good example of how to do things right.

**Comment by phobson** [comment]
:+1: I'll look into loading `gridgen`.
