### ISSUE TITLE
create conda package

### ISSUE THREAD

**Issue by rsignell-usgs** [hetland/pygridgen#7]
It would be great to create a conda package for pygridgen so that conda users could just do:
`conda install pygridgen` and be done with it.
@phobson, I see you are a conda fan -- do you have experience building conda packages?

**Comment by phobson** [comment]
Unfortunately I do not. I've been going through your packages on binstar trying to figure it out. I'm got three PRs headed this way shortly, and one of them hooks `pygridgen` up to Travis CI with a build/install script (and some unit tests). That's gotta be worth something, right?

**Comment by phobson** [comment]
@hetland @rsignell-usgs 

I figured it out!

In Linux you can:

```
conda create --name=grids python=2.7 nose pip ipython-notebook
source activate grids
conda install --channel=phobson nn csa gridutils gridgen pygridgen
```

And then the examples in the readme file work!

I'll try to get this working on OS X soon.

**Comment by rsignell-usgs** [comment]
Way to go Paul!!!! 
It worked flawlessly for me!
http://nbviewer.ipython.org/github/rsignell-usgs/notebook/blob/9470773aa8d783991fd12af419811f22c8134b04/pygridgen_test.ipynb

**Comment by phobson** [comment]
Thanks for testing, Rich.

I'll add notes to the conda recipes explaining the build process gymnastics
I had to go through to get this to work.

The weird thing is that the testing infrastructure requires an older
version of gridutils (0.43), but I got this to work with the latest version
(0.52).

I'll also update the Linux installation docs and try to make a Mac OS X
build too.
